# Generated by Django 5.0 on 2023-12-22 04:05

import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='reactions',
            field=models.CharField(default='5', max_length=20),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='updated',
            field=home.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
