# Generated by Django 5.0 on 2023-12-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_notesmodel_reactions_alter_notesmodel_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='body',
            field=models.CharField(max_length=2200),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='reactions',
            field=models.CharField(max_length=50),
        ),
    ]
