# Generated by Django 5.0 on 2024-01-05 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_notesmodel_body_alter_notesmodel_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFuturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SYMBOL', models.CharField(default=None, max_length=120)),
                ('OPEN', models.FloatField(default=0.0)),
                ('HIGH', models.FloatField(default=0.0)),
                ('LOW', models.FloatField(default=0.0)),
                ('CLOSE', models.FloatField(default=0.0)),
                ('VOLUME', models.FloatField(default=0.0)),
                ('OPEN_INT', models.CharField(default=None, max_length=120)),
                ('CHG_IN_OI', models.FloatField(default=0.0)),
                ('TIMESTAMP', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
