# Generated by Django 5.0 on 2024-01-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_stockfuturesmodel_open_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='body',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
