# Generated by Django 5.0 on 2024-02-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarFlix', '0002_ffmoviedetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffmoviedetailsmodel',
            name='Watched',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
