# Generated by Django 5.0 on 2024-02-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarFlix', '0003_ffmoviedetailsmodel_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farflixmoviesmodel',
            name='movieName_Disk',
            field=models.CharField(default=None, editable=False, max_length=220),
        ),
    ]
