# Generated by Django 5.0 on 2024-02-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarFlix', '0004_alter_farflixmoviesmodel_moviename_disk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farflixmoviesmodel',
            name='movieName_Disk',
            field=models.CharField(default=None, max_length=220),
        ),
    ]
