# Generated by Django 5.0 on 2024-02-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarFlix', '0005_alter_farflixmoviesmodel_moviename_disk'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffmoviedetailsmodel',
            name='Country_IMDB',
            field=models.CharField(default=None, max_length=130),
        ),
    ]
