# Generated by Django 5.0 on 2024-01-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockEquitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SYMBOL', models.CharField(default=None, max_length=120)),
                ('OPEN', models.FloatField(default=0.0)),
                ('HIGH', models.FloatField(default=0.0)),
                ('LOW', models.FloatField(default=0.0)),
                ('CLOSE', models.FloatField(default=0.0)),
                ('TOTTRDQTY', models.CharField(default=None, max_length=120)),
                ('TOTTRDVAL', models.CharField(blank=True, default=None, editable=False, max_length=120, null=True)),
                ('TIMESTAMP', models.CharField(default=None, max_length=120)),
            ],
        ),
    ]
