# Generated by Django 5.0 on 2024-04-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equityHome', '0003_alter_indexhistoricalmodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexhistoricalmodel',
            name='TIMESTAMP',
            field=models.DateField(default=None),
        ),
    ]
